---
title: "Activity Monitoring"
author: "Someshwar Rao Sattiraju"
date: "May 19, 2017"
output: md_document
---

Personal activity monitoring device are quite common now a days for keeping track on fitness and other activities. We have gadgets and smartphones which can capture activities and provide information with graphics on how many calories we burn or how much we exercised in a given day. 

This particular data set consists of data provided by a devices which collects data at 5 minute intervals through out the day. The data consists of two months of data from an anonymous individual collected during the months of October and November, 2012 and include the number of steps taken in 5 minute intervals each day.

This data is taken from 

1. Code for reading the data and processing the data
```{R Data Ready, echo = TRUE}
library(ggplot2)
data<-read.csv("S:/Software/R/Data Science Specialization/Reproducible Research/Week2/activity.csv")
head(data)
tail(data)
good<-complete.cases(data$steps)
newdata<-data[good,]
```


2. Histogram of total numbr of steps taken each day
```{R Histogram Total Steps Taken, echo=TRUE}
dt<-aggregate(newdata$steps,list(date=newdata$date),sum)
ggplot(dt,aes(date,x))+geom_bar(stat="Identity",fill = "blue")+ylab("Count")+xlab("Date")+ggtitle("Histogram of Total Number Of Steps Taken Each Day")+theme(axis.text.x=element_text(angle=90, hjust=1))
dev.copy(png,"S:/Software/R/Data Science Specialization/Reproducible Research/Week2/hist1.png")
dev.off()


```

3. Mean And Median Number Of Steps Taken Each Day
```{R Mean And Median Steps Take Each Day, echo = TRUE }
data1<-newdata[newdata$steps!=0,]
meansteps<-data.frame(aggregate(data1$steps,list(date=data1$date),mean))
mediansteps<-aggregate(data1$steps,list(date=data1$date),median)
names(meansteps)<-c("Date","Meansteps")
names(mediansteps)<-c("Date","Mediansteps")
print("Mean Number Of Steps Taken Each Day")
print(meansteps)
print("Median Number of Steps Taken Each Day")
print(mediansteps)
```

4. Time Series Plot Of Average Number Of Steps Taken Each Day
```{R Time Series Plot, echo = TRUE}

ggplot(meansteps,aes(Date,Meansteps,group=1))+geom_line(colour="Blue")+ylab("Steps")+xlab("Date")+ggtitle("Time Series Plot Of Mean Steps Taken Each Day")+theme(axis.text.x=element_text(angle=90, hjust=1))
dev.copy(png,"S:/Software/R/Data Science Specialization/Reproducible Research/Week2/timeseries.png")
dev.off()
```

5. The 5-minute interval that, on average, contains the maximum number of steps
```{R 5 Min Interval Where Maximum Steps are Taken, echo = TRUE}
meanvalue<-tapply(newdata$steps,newdata$interval,mean)
plot(meanvalue,type="l",col="Blue",ylab="Steps",xlab="5 Min - Interval", main= " Plot Of Maximum Steps Taken At 5 Min Interval On Average ")
dev.copy(png,"S:/Software/R/Data Science Specialization/Reproducible Research/Week2/tsfive.png")
dev.off()
```

6. Code For Imputing Missing Values
```{R Code For Missing Values, echo=TRUE}
library(mice)
md.pattern(data)
impute_data<-mice(data,m=5,maxit=50,method='pmm',seed=500)
impute_data$imp$steps
completeData<-complete(impute_data,2)
```

7. Histogram of the total number of steps taken each day after missing values are imputed
```{R Code For Histogram,echo=TRUE}
dt<-aggregate(completeData$steps,list(date=completeData$date),sum)
ggplot(dt,aes(date,x))+geom_bar(stat="Identity",fill = "blue")+ylab("Count")+xlab("Date")+ggtitle("Histogram of Total Number Of Steps Taken Each Day")+theme(axis.text.x=element_text(angle=90, hjust=1))
dev.copy(png,"S:/Software/R/Data Science Specialization/Reproducible Research/Week2/hist2.png")
dev.off()
```

8. Panel plot comparing the average number of steps taken per 5-minute interval across weekdays and weekends
```{R Avg Number of steps taken per 5-minute interval across weekdays and weekends,echo=TRUE}
library(lattice)
newdata$day<-"weekday"
newdata$day[weekdays(as.Date(newdata$date),abb=T) %in% c("Sat","Sun")]<-"weekend"
wdata<-aggregate(steps~interval+day, data=newdata,FUN="mean")

xyplot(steps~interval | day, data = wdata, type="l",grid=T,layout=c(1,2), col="Blue",ylab="Number of Steps",xlab="5 Min - Interval", main= " Average 5 Min Activity Intervals For Weeday Vs Weekend")
dev.copy(png,"S:/Software/R/Data Science Specialization/Reproducible Research/Week2/weekendvsweekday.png")
dev.off()
```
